//! Air-interface encryption (ETSI EN 300 392-7 clause 6).
//!
//! For each protected MAC PDU a fresh key stream segment (KSS) is generated by
//! the cell's KSG from the encryption cipher key ECK and the initial value IV
//! of the burst carrying it. KSS(0) is XORed with the first bit of the TM-SDU
//! and so on; the MAC header and fill bits stay clear. A logical channel in
//! the second half of a slot uses the key stream from bit 216 (Table 6.4).
//!
//! ECK is derived from the cipher key (SCK in a class 2 cell) with TB5, so
//! that the same key gives a different stream on every carrier / colour code /
//! location area.

use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::keys::CipherKey;
use crate::ksg::{Iv, KsgId, new_ksg};
use crate::taa1;

/// Where in the key stream a logical channel's protection starts (Table 6.4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KssOffset {
    /// Full slot, or the first half slot: KSS(0 …).
    First = 0,
    /// The second half slot (SCH/HD, STCH, SCH-P8/HD): KSS(216 …).
    Second = 216,
}

/// The cell's encryption parameters for security class 2 (clause 6.5.1.2).
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct Class2Keys {
    #[zeroize(skip)]
    pub ksg: KsgId,
    /// The static cipher key in use.
    pub sck: CipherKey,
    /// SCK number, 1 … 32 (broadcast in SYSINFO).
    #[zeroize(skip)]
    pub sckn: u8,
    /// SCK version number; its least significant bit goes into the encryption
    /// mode element of every encrypted downlink MAC header.
    #[zeroize(skip)]
    pub sck_vn: u16,
}

impl Class2Keys {
    /// The encryption mode element value for an encrypted downlink PDU
    /// (Table 6.6): `10` for an even SCK-VN, `11` for an odd one.
    pub fn encryption_mode(&self) -> u8 {
        0b10 | (self.sck_vn & 1) as u8
    }

    /// The encrypted short identity of an SSI under this SCK (clause 4.2.6).
    pub fn esi(&self, ssi: u32) -> u32 {
        taa1::ta61(&self.sck.0, ssi)
    }

    /// The SSI behind an ESI a radio used.
    pub fn ssi_from_esi(&self, esi: u32) -> u32 {
        taa1::ta61_inverse(&self.sck.0, esi)
    }

    /// Bind the key to this cell (clause 4.2.7): `cn` carrier number,
    /// `la` location area, `cc` colour code.
    pub fn eck(&self, cn: u16, la: u16, cc: u8) -> CipherKey {
        CipherKey(taa1::tb5(&self.sck.0, cn, la, cc))
    }
}

/// Key stream bits for one logical channel: `len` bits starting at `offset`,
/// one bit per returned byte (0/1), as FlowStation's bit arrays are laid out.
pub fn key_stream(ksg: KsgId, eck: &CipherKey, iv: Iv, offset: KssOffset, len: usize) -> Option<Vec<u8>> {
    let mut g = new_ksg(ksg, eck, iv)?;
    let skip = offset as usize;
    let total = skip + len;
    let mut out = Vec::with_capacity(len);
    let mut produced = 0usize;
    while produced < total {
        let byte = g.next_byte();
        for bit in (0..8).rev() {
            if produced >= skip && produced < total {
                out.push((byte >> bit) & 1);
            }
            produced += 1;
        }
    }
    Some(out)
}

/// XOR a bit array (one bit per byte) in place with the key stream for this
/// burst. Encryption and decryption are the same operation.
pub fn apply(ksg: KsgId, eck: &CipherKey, iv: Iv, offset: KssOffset, bits: &mut [u8]) -> bool {
    let Some(kss) = key_stream(ksg, eck, iv, offset, bits.len()) else {
        return false;
    };
    for (b, k) in bits.iter_mut().zip(kss) {
        *b ^= k;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ksg::{Ksg, Tea3};

    fn keys() -> Class2Keys {
        Class2Keys {
            ksg: KsgId::Tea3,
            sck: "00112233445566778899".parse().unwrap(),
            sckn: 1,
            sck_vn: 7,
        }
    }

    #[test]
    fn mode_element_follows_sck_vn_parity() {
        assert_eq!(keys().encryption_mode(), 0b11);
        let mut k = keys();
        k.sck_vn = 8;
        assert_eq!(k.encryption_mode(), 0b10);
    }

    #[test]
    fn esi_round_trips_and_differs_from_ssi() {
        let k = keys();
        let esi = k.esi(2358245);
        assert_ne!(esi, 2358245);
        assert!(esi < 1 << 24);
        assert_eq!(k.ssi_from_esi(esi), 2358245);
    }

    #[test]
    fn key_stream_matches_the_generator_bit_for_bit() {
        let eck = keys().eck(1521, 2, 1);
        let iv = Iv::from_frame(1, 6, 30, 110, false);
        let mut g = Tea3::new(&eck.0, iv);
        let mut reference = Vec::new();
        for _ in 0..60 {
            let b = g.next_byte();
            reference.extend((0..8).rev().map(|i| (b >> i) & 1));
        }
        assert_eq!(key_stream(KsgId::Tea3, &eck, iv, KssOffset::First, 268).unwrap(), reference[..268]);
        assert_eq!(
            key_stream(KsgId::Tea3, &eck, iv, KssOffset::Second, 124).unwrap(),
            reference[216..340]
        );
    }

    #[test]
    fn apply_is_an_involution_and_direction_dependent() {
        let eck = keys().eck(1521, 2, 1);
        let plain: Vec<u8> = (0..124).map(|i| (i % 3 == 0) as u8).collect();
        let dl = Iv::from_frame(2, 3, 4, 5, false);
        let mut bits = plain.clone();
        assert!(apply(KsgId::Tea3, &eck, dl, KssOffset::First, &mut bits));
        assert_ne!(bits, plain);
        apply(KsgId::Tea3, &eck, dl, KssOffset::First, &mut bits);
        assert_eq!(bits, plain);
        let mut other = plain.clone();
        apply(KsgId::Tea3, &eck, Iv::from_frame(2, 3, 4, 5, true), KssOffset::First, &mut other);
        let mut again = plain.clone();
        apply(KsgId::Tea3, &eck, dl, KssOffset::First, &mut again);
        assert_ne!(other, again, "uplink and downlink streams differ");
        assert!(!apply(KsgId::Tea4, &eck, dl, KssOffset::First, &mut again), "TEA4 is not provided");
        assert!(
            apply(KsgId::Tea1, &eck, dl, KssOffset::First, &mut again),
            "TEA1 is provided (weak)"
        );
    }
}
